name: Upload ZIP to Existing Release

on:
  push:
    tags:
      - 'v*'

jobs:
  upload-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP Archive
        run: |
          zip -r release-${{ github.ref_name }}.zip README.md manifest.json LICENSE content.js popup icons

      - name: Upload ZIP to Existing Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
